app_container/flightx/urls.py
from django.contrib import admin
from django.urls import path
from airlinex.views import *
from airportx.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', StartpageView.as_view(), name='Home'),
    path('startpage/', StartpageView.as_view(), name='Home'),

    path('aircrafts/', AircraftListView.as_view(), name='Aircrafts'),
    path('airport-si-check/', AirportSICheck.as_view(), name='AirportsSICheck'),
    path('aircrafts/add/', AircraftCreateView.as_view(), name='AddAircrafts'),
    path('aircrafts/<slug:pk>/', AircraftUpdateView.as_view(),
         name='UpdateAircrafts'),
    path('aircrafts/<slug:pk>/delete/',
         AircraftDeleteView.as_view(), name='DeleteAircrafts'),

    path('airports/', AirportListView.as_view(), name='Airports'),
    path('airports/add/', AirportCreateView.as_view(), name='AddAirports'),
    path('airports/<slug:pk>/', AirportUpdateView.as_view(), name='UpdateAirports'),
    path('airports/<slug:pk>/delete/',
         AirportDeleteView.as_view(), name='DeleteAirports'),
    path('airports/<slug:pk>/materializedview/',
         AirportDetailView, name='AirportsMView'),

    path('runways/', RunwayListView.as_view(), name='Runways'),
    path('runways/add/', RunwayCreateView.as_view(), name='AddRunways'),
    path('runways/<slug:pk>/', RunwayUpdateView.as_view(), name='UpdateRunways'),
    path('runways/<slug:pk>/delete/',
         RunwayDeleteView.as_view(), name='DeleteRunways'),

    path('assignments/', AssignmentListView.as_view(), name='Assignments'),
    path('assignments/add/', AssignmentCreateView.as_view(), name='AddAssignments'),
    path('assignments/<slug:pk>/', AssignmentUpdateView.as_view(),
         name='UpdateAssignments'),
    path('assignments/<slug:pk>/delete/',
         AssignmentDeleteView.as_view(), name='DeleteAssignments'),

    path('bookings/', BookingListView.as_view(), name='Bookings'),
    path('bookings/add/', BookingCreateView.as_view(), name='AddBookings'),
    path('bookings/<slug:pk>/', BookingUpdateView.as_view(), name='UpdateBookings'),
    path('bookings/<slug:pk>/delete/',
         BookingDeleteView.as_view(), name='DeleteBookings'),

    path('employees/', EmployeeListView.as_view(), name='Employees'),
    path('employees/add/', EmployeeCreateView.as_view(), name='AddEmployees'),
    path('employees/<slug:pk>/', EmployeeUpdateView.as_view(),
         name='UpdateEmployees'),
    path('employees/<slug:pk>/delete/',
         EmployeeDeleteView.as_view(), name='DeleteEmployees'),

    path('flights/', FlightListView.as_view(), name='Flights'),
    path('flights/add/', FlightsCreateView.as_view(), name='AddFlights'),
    path('flights/<slug:pk>/', FlightsUpdateView.as_view(), name='UpdateFlights'),
    path('flights/<slug:pk>/delete/',
         FlightsDeleteView.as_view(), name='DeleteFlights'),

    path('passengers/', PassengerListView.as_view(), name='Passengers'),
    path('passengers/add/', PassengerCreateView.as_view(), name='AddPassengers'),
    path('passengers/<slug:pk>/', PassengerUpdateView.as_view(),
         name='UpdatePassengers'),
    path('passengers/<slug:pk>/delete/',
         PassengerDeleteView.as_view(), name='DeletePassengers'),
]

app_container/airlinex/models.py
from django.db import models
from airportx.models import Airport


class Aircraft(models.Model):
    """
    A class used to represent an aircrafts

    Attributes
    ----------
    registration : str
        the unique aircraft registration
    type_series : str
        the type of aircraft
    passenger_capacity : int
        number of passengers the aircraft can carry
    """

    # Choices for different Aircraft types
    TYPE_SERIES_CHOICES = [
        ("A388", "A380-800"),
        ("A358", "A350-800"),
        ("A359", "A350-900"),
        ("A3501", "A350-1000"),
        ("A3201", "A320-100"),
        ("A3202", "A320-200"),
        ("A320n", "A320neo"),
        ("B772", "B777-200"),
        ("B773", "B777-300"),
        ("B788", "B787-8"),
        ("B789", "B787-9"),
        ("B744", "B747-400"),
        ("B748", "B747-8I"),
        ("B73710", "B737-MAX10"),
    ]

    # Model Attributes
    registration = models.CharField(
        "Unique aircraft registration", max_length=10, primary_key=True)
    type_series = models.CharField(
        "Aircraft type series", max_length=10, choices=TYPE_SERIES_CHOICES)
    passenger_capacity = models.IntegerField("Number of passenger seats")

    # Class functions
    def __str__(self) -> str:
        return f"{self.get_type_series_display()} ({self.registration})"


class Passenger(models.Model):
    """
    A class used to represent passengers

    Attributes
    ----------
    first_name : str
        the first name of the customer
    last_name : str
        the last name of the customer
    status : str
        the customer status (Bronze, Silver, Gold, Platinum)
    notes : str
        customer specific notes such as preferences
    """

    # Customer status options
    CUSTOMER_STATUS_CHOICES = [
        ("B", "Bronze"),
        ("S", "Silver"),
        ("G", "Gold"),
        ("P", "Platinum"),
    ]

    # Model Attributes
    first_name = models.CharField("First name", max_length=100)
    last_name = models.CharField("Last name", max_length=100, db_index=True)
    status = models.CharField(
        "Customer status", max_length=20, choices=CUSTOMER_STATUS_CHOICES, default="B")
    notes = models.TextField("Extra notes", max_length=2000, blank=True)

    # Class functions
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


class Employee(models.Model):
    """
    A class used to represent employees

    Attributes
    ----------
    first_name : str
        the first name of the employee
    last_name : str
        the last name of the employee
    email : str
        the employee email address 
    role : str
        the role of the employee 
    based_in : obj
        relationship to the airport (Airport) the employee is based at
    spouse : obj
        relationship to the the spouse (Employee) if applicable
    """

    # Choices for employee role
    EMPLOYEE_ROLE_CHOICES = [
        ("C", "Captain"),
        ("FO", "First Officer"),
        ("SO", "Second Officer"),
        ("CC", "Cabin Crew"),
    ]

    # Model Attributes
    first_name = models.CharField("First name", max_length=100)
    last_name = models.CharField("Last name", max_length=100, db_index=True)
    email = models.EmailField("Employee mail")
    role = models.CharField("Employee role:", max_length=2,
                            choices=EMPLOYEE_ROLE_CHOICES)
    based_in = models.ForeignKey(Airport, on_delete=models.SET_NULL, null=True)
    spouse = models.OneToOneField(
        'self', on_delete=models.SET_NULL, related_name='spouse_of', null=True, blank=True)

    # Class functions
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


class Flight(models.Model):
    """
    A class used to represent flights

    Attributes
    ----------
    number : str
        the flight number
    departure_airport : obj
        relationship to the departure airport
    destination_airport : obj
        relationship to the destination airport 
    aircraft : obj
        relationship to the aircraft for the flight
    departure_time : obj
        time the aircraft is sceduled to depart the departure_airport
    arrival_time : obj
        time the aircraft is sceduled to arrive at the destination_airport
    delay : int
        the delay of the flight in minutes
    cancelled : bool
        the cancelled status of the flight
    employees : obj
        flight crew as a many to many relationship with Employee through Assignment
    """

    # Model Attributes
    number = models.CharField("Flight number", max_length=10, primary_key=True)
    departure_airport = models.ForeignKey(
        Airport, on_delete=models.CASCADE, related_name="departure_airport")
    destination_airport = models.ForeignKey(
        Airport, on_delete=models.CASCADE, related_name="arrival_airport")
    aircraft = models.ForeignKey(
        Aircraft, on_delete=models.PROTECT, related_name="aircraft")

    departure_time = models.DateTimeField("Departure Date & Time")
    arrival_time = models.DateTimeField("Arrival Date & Time")
    delay = models.PositiveIntegerField("Delay in minutes", default=0)
    cancelled = models.BooleanField("Cancelation status", default=False)

    employees = models.ManyToManyField(Employee, through='Assignment')

    # Class functions
    def get_duration(self) -> int:
        """Return flight duration in minutes"""

        return self.arrival_time - self.departure_time

    def __str__(self) -> str:
        return f"Flight {self.number} from {self.departure_airport} to {self.destination_airport}"


class Assignment(models.Model):
    """
    A class used to represent assignment of employees to flights

    Attributes
    ----------
    employee : obj
        relationship to the employee assigned
    flight : obj
        relationship to the flight the employee was assigned to 
    """

    # Model Attributes 
    # Cannot delete Employee without replacement for assigments
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE)

    # Class functions
    def __str__(self) -> str:
        return f"Employee {self.employee.first_name} {self.employee.last_name} on flight {self.flight.number}"


class Booking(models.Model):
    """
    A class used to represent flights bookings of passenger

    Attributes
    ----------
    flight : obj
        relationship to the booked flight
    passenger : obj
        relationship to the passenger who booked the flight 
    time : obj
        the time the booking was made
    cancelled : obj
        set to true if the respective flight was canceled (sql procedure)
    """

    # Model Attributes 
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE)
    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)
    time = models.DateTimeField("Creation time of booking", auto_now_add=True)
    cancelled = models.BooleanField("Cancelation status", default=False)

    # Uniqueness contrains to prevent one customer booking the same flight twice
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['flight', 'passenger'], name='flight_passenger_unique')
        ]

    def __str__(self) -> str:
        return f"Passenger {self.passenger.first_name} {self.passenger.last_name} on flight {self.flight.number}"

app_container/airlinex/forms.py
from django import forms
from .models import Flight, Employee


class FlightFormCreate(forms.ModelForm):
    class Meta:
        model = Flight
        fields = ['number', 'departure_airport', 'destination_airport', 'aircraft',
                  'departure_time', 'arrival_time', 'delay', 'cancelled']
        widgets = {
            'departure_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'arrival_time': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }


class FlightFormUpdate(forms.ModelForm):
    class Meta:
        model = Flight
        fields = ['departure_airport', 'destination_airport', 'aircraft',
                  'departure_time', 'arrival_time', 'delay', 'cancelled']
        widgets = {
            'departure_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'arrival_time': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }


class EmployeeForm(forms.ModelForm):
    """
    Customize the Employee form to exclude the selected employee itself from the potential spouses list.
    """
    
    spouse = forms.ModelChoiceField(
        queryset=Employee.objects.all(), required=False)

    def __init__(self, *args, **kwargs):
        current_employee = kwargs.pop('current_employee', None)
        super().__init__(*args, **kwargs)
        if current_employee:
            self.fields['spouse'].queryset = Employee.objects.exclude(
                pk=current_employee.pk)

    class Meta:
        model = Employee
        fields = ['first_name', 'last_name',
                  'email', 'role', 'based_in', 'spouse']

app_container/airlinex/templates/airlinex/aircraft_confirm_delete.html
{% extends "base.html" %}

{% block title %}Airports{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Please confirm that you want to delete the Aircraft "{{aircraft.registration}}":</p>
        <button type="submit">Confirm</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/aircraft_list.html
{% extends "base.html" %}

{% block title %}Aircrafts{% endblock %}

{% block content %}
<div class="table-container">
    <table>
        <tr>
            <th>Registration</th>
            <th>Type Series</th>
            <th>Passenger Capacity</th>
            <th>Actions</th>
        </tr>
        {% for aircraft in object_list %}
        <tr>
            <td>{{ aircraft.registration }}</td>
            <td>{{ aircraft.get_type_series_display }}</td>
            <td>{{ aircraft.passenger_capacity }}</td>
            <td>
                <a href="{% url 'UpdateAircrafts' aircraft.registration %}"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'DeleteAircrafts' aircraft.registration %}"><i class="bi bi-trash"></i></a>
                <!-- Old Edit: &#9998; Delete: &#128465; -->
            </td>
        </tr>
        {% endfor %}
    </table>
    <a class="add_link" href="{% url 'AddAircrafts' %}">Add Aircraft</a>
</div>
{% endblock %}

app_container/airlinex/templates/airlinex/assignment_form.html
{% extends "base.html" %}

{% block title %}Assignments{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/assignment_list.html
{% extends "base.html" %}

{% block title %}Assignments{% endblock %}

{% block content %}
<div class="table-container">
    <table>
        <tr>
            <th>Flight</th>
            <th>From</th>
            <th>To</th>
            <th>Assignee</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
        {% for assignment in object_list %}
        <tr>
            <td>{{ assignment.flight.number }}</td>
            <td>{{ assignment.flight.departure_airport.name }}</td>
            <td>{{ assignment.flight.destination_airport.name }}</td>
            <td>{{ assignment.employee.first_name }} {{ assignment.employee.last_name }}</td>
            <td>{{ assignment.employee.get_role_display }}</td>
            <td>
                <a href="{% url 'UpdateAssignments' assignment.id %}"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'DeleteAssignments' assignment.id %}"><i class="bi bi-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <a class="add_link" href="{% url 'AddAssignments' %}">Add Assignment</a>
</div>
{% endblock %}

app_container/airlinex/templates/airlinex/booking_confirm_delete.html
{% extends "base.html" %}

{% block title %}Booking{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Please confirm that you want to delete the booking of "{{booking.passenger}}" for Flight "{{booking.flight}}":</p>
        <button type="submit">Confirm</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/booking_form.html
{% extends "base.html" %}

{% block title %}Bookings{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/booking_list.html
{% extends "base.html" %}

{% block title %}Bookings{% endblock %}

{% block content %}
<div class="table-container">
    <table>
        <tr>
            <th>Flight</th>
            <th>From</th>
            <th>To</th>
            <th>Passenger</th>
            <th>Passenger Notes</th>
            <th>Actions</th>
        </tr>
        {% for booking in object_list %}
        <tr>
            <td {% if booking.cancelled %} style="text-decoration: line-through;"{% endif %}>{{ booking.flight.number }}</td>
            <td {% if booking.cancelled %} style="text-decoration: line-through;"{% endif %}>{{ booking.flight.departure_airport.name }}</td>
            <td {% if booking.cancelled %} style="text-decoration: line-through;"{% endif %}>{{ booking.flight.destination_airport.name }}</td>
            <td {% if booking.cancelled %} style="text-decoration: line-through;"{% endif %}>{{ booking.passenger.first_name }} {{ booking.passenger.last_name }}</td>
            <td {% if booking.cancelled %} style="text-decoration: line-through;"{% endif %}>{{ booking.passenger.notes }}</td>
            <td>
                <a href="{% url 'UpdateBookings' booking.id %}"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'DeleteBookings' booking.id %}"><i class="bi bi-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <a class="add_link" href="{% url 'AddBookings' %}">Add Booking</a>
</div>
{% endblock %}

app_container/airlinex/templates/airlinex/employee_confirm_delete.html
{% extends "base.html" %}

{% block title %}Employees{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Please confirm that you want to delete the employee "{{employee.first_name}} {{employee.last_name}}":</p>
        <button type="submit">Confirm</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/employee_form.html
{% extends "base.html" %}

{% block title %}Employee{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/employee_list.html
{% extends "base.html" %}

{% block title %}Crew{% endblock %}

{% block content %}
<div class="table-container">
    <table>
        <tr>
            <th>Name</th>
            <th>E-Mail</th>
            <th>Role</th>
            <th>Based In</th>
            <th>Spouse</th>
            <th>Actions</th>
        </tr>
        {% for employee in object_list %}
        <tr>
            <td>{{ employee.first_name }} {{ employee.last_name }} 
                {% if top_hours_pilot_id and top_hours_pilot_id == employee.id %}<span class="badge"><i class="bi bi-trophy-fill"></i> AIRTIME</span>{% endif %}
                {% if top_flights_pilot_id and top_flights_pilot_id == employee.id %}<span class="badge"><i class="bi bi-trophy-fill"></i> #FLIGHTS</span>{% endif %}
            </td>
            <td>{{ employee.email }}</td>
            <td>{{ employee.get_role_display }}</td>
            <td>{{ employee.based_in.name }}</td>
            <td>{% if employee.spouse %}{{ employee.spouse.first_name }} {{ employee.spouse.last_name }}{% else %} - {% endif %}</td>
            <td>
                <a href="{% url 'UpdateEmployees' employee.id %}"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'DeleteEmployees' employee.id %}"><i class="bi bi-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <a class="add_link" href="{% url 'AddEmployees' %}">Add Crew member</a>
</div>
{% endblock %}

app_container/airlinex/templates/airlinex/flight_confirm_delete.html
{% extends "base.html" %}

{% block title %}Flights{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Please confirm that you want to delete Flight Nr. "{{flight.number}}":</p>
        <button type="submit">Confirm</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/passenger_confirm_delete.html
{% extends "base.html" %}

{% block title %}Passenger{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Please confirm that you want to delete the Passenger "{{passenger.first_name}} {{passenger.last_name}}":</p>
        <button type="submit">Confirm</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/passenger_form.html
{% extends "base.html" %}

{% block title %}Passengers{% endblock %}

{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</div>

{% endblock %}

app_container/airlinex/templates/airlinex/passenger_list.html
{% extends "base.html" %}

{% block title %}Passengers{% endblock %}

{% block content %}

<div class="table-container">
    <table>
        <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Notes</th>
            <th>Actions</th>
        </tr>
        {% for passenger in object_list %}
        <tr>
            <td>{{ passenger.first_name }} {{ passenger.last_name }}
                {% if all_time_passenger_id and all_time_passenger_id == passenger.id %}<span class="badge"><i class="bi bi-trophy-fill"></i> ALL TIME PASSENGER</span>{% endif %}
            </td>
            <td>{{ passenger.get_status_display }}</td>
            <td>{{ passenger.notes }}</td>
            <td>
                <a href="{% url 'UpdatePassengers' passenger.id %}"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'DeletePassengers' passenger.id %}"><i class="bi bi-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <a class="add_link" href="{% url 'AddPassengers' %}">Add Passenger</a>
</div>
{% endblock %}